# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - path_regex: .*.ya?ml
    encrypted_regex: '^(data|stringData)$'
    age: "age16ljjgt8uu24vv7qrjul2zjdxfw4krad75ctlncypygg0xrx4guhsqqnrjt"
