apiVersion: v1
data:
    hello: ENC[AES256_GCM,data:E/2+K/kut4wJOWAy+S7wY7F2lTrlL7Mv,iv:LPnNhtOeoLferXMH8nJWUI+HVCfRlInEHGMRFo3+T0A=,tag:JIqSEp0aXfcA3FVZzw9Q9Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q704esh8hjphy28k5chagx0dujh3l0leu7zl3n7khvy5k9mnselsahtz6y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1U2tBSjdkeTBWM3Zud2ZL
            bUtEMnVUcFNwa3VxVWE5NldpR0o1d05MOUhBCmRlZm16QzBKNXFnYTFDY1U3MitU
            WlIrR282ZmRPMWRMK1BGUkhFK1lBYjQKLS0tIFBGUnZyQi9wTFE4RXAxRFMzd0hP
            MFVhOXQyTGpHcmJIUGZpZVVoVHI1bzgKn8bti3XBb8ZYN+eWvC6Q5+9HdKo9aMYk
            bNxTMeBf1wAYC5BA2PH3CC4tnFyjzphKkr1v6g6AdRIO0u9WlraZgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-12T12:31:26Z"
    mac: ENC[AES256_GCM,data:Z+wqS1u6YohySAzR7qCNyfc8uH3ktIPDj9ukoY/AZvnleF98doPgkvAO0K8l1XPQ5khtg2HbRe8nAF1Az5aAYC7kn2qV7DqUzu/wJpMGe6zkRCSAEf+n/WMFWuz3vIGATqMxcwpEewbACVEodeuQEwblKuOLBZFHQqyZqqp6Ets=,iv:VtmXCXecm9bvVIX7DRwbFKcm/qd71x7UdsReUAITVic=,tag:zXndAbVFm2j/5NsB8m+RrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
